# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: brewstore

namespace: brewstore

registry: murilobeltrame

extensions:
- name: zipkin
- name: seq
  logPath: ./.logs

ingress:
- name: ingress
  bindings:
    - port: 8080
  rules:
    - host: razor.app.local
      service: brewstore-web

    - host: server.blazor.app.local
      service: brewstore-blazorserver

    - host: wasm.blazor.app.local
      service: brewstore-blazorwasm
    

    - path: /api
      service: brewstore-api
    - host: api.app.local
      service: brewstore-api



services:
- name: brewstore-api
  project: BrewStore.Api/BrewStore.Api.csproj
- name: brewstore-api-db
  image: postgres:13.4
  env:
    - name: POSTGRES_PASSWORD
      value: "4authpass@word"
  bindings:
    - port: 54321
      containerPort: 5432
      connectionString: Server=${host};Port=${port};User Id=postgres;Password=${env:POSTGRES_PASSWORD};
- name: brewstore-api-cache
  image: redis
  bindings:
  - port: 63791
    containerPort: 6379
    connectionString: "${host}:${port}"

- name: brewstore-web
  project: BrewStore.Web/BrewStore.Web.csproj

- name: brewstore-blazorserver
  project: BrewStore.BlazorServer/BrewStore.BlazorServer.csproj

- name: brewstore-blazorwasm
  project: BrewStore.BlazorWasm/Server/BrewStore.BlazorWasm.Server.csproj